DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE AUTHORS(ID INT PRIMARY KEY, NAME VARCHAR(255));

DROP TABLE IF EXISTS GENRES;
CREATE TABLE GENRES(ID INT PRIMARY KEY, NAME VARCHAR(255));

DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS(ID INT PRIMARY KEY, NAME VARCHAR(255), GENRE_ID INT);
-- FOREIGN KEY (GENRE_ID) REFERENCES GENRES(ID));

DROP TABLE IF EXISTS BOOKS_AUTHORS;
CREATE TABLE BOOKS_AUTHORS(BOOK_ID INT , AUTHOR_ID INT, PRIMARY KEY(BOOK_ID, AUTHOR_ID));
-- FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(ID), FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS(ID));